### ISSUE TITLE
Unable to make pyzmq work on pypy 5.1.1 32 bit on Windows

### ISSUE THREAD

**Issue by sakurai-youhei** [zeromq/pyzmq#852]
**Error on use of pyzmq-15.3.0.dev0**

When importing pyzmq, compilation claims that "sys/un.h" doesn't exist although there shouldn't be such "sys/un.h" because of Windows.

```
C:\Users\Administrator>pypy -c "import zmq"
_cffi_ext.c
C:\pypy-5.1.1-win32\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(53) : fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\pypy-5.1.1-win32\site-packages\zmq\__init__.py", line 56, in <module>
    from zmq import backend
  File "C:\pypy-5.1.1-win32\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\pypy-5.1.1-win32\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\pypy-5.1.1-win32\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\pypy-5.1.1-win32\site-packages\zmq\backend\cffi\__init__.py", line 6, in <module>
    from zmq.backend.cffi import (constants, error, message, context, socket,
  File "C:\pypy-5.1.1-win32\site-packages\zmq\backend\cffi\constants.py", line 4, in <module>
    from ._cffi import C, c_constant_names
  File "C:\pypy-5.1.1-win32\site-packages\zmq\backend\cffi\_cffi.py", line 100, in <module>
    "Please check that you have zeromq headers and libraries." % e)
ImportError: PyZMQ CFFI backend couldn't find zeromq: CompileError: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
Please check that you have zeromq headers and libraries.
```

**Error on installation of pyzmq-15.2.0**

Building ZeroMQ doesn't seem to work well.

```
C:\Users\Administrator>pypy -m pip install pyzmq
Collecting pyzmq
  Using cached pyzmq-15.2.0.zip
Requirement already satisfied (use --upgrade to upgrade): py in c:\pypy-5.1.1-win32\site-packages (from pyzmq)
Requirement already satisfied (use --upgrade to upgrade): cffi in c:\pypy-5.1.1-win32\lib_pypy (from pyzmq)
Installing collected packages: pyzmq
  Running setup.py install for pyzmq

...

    LINK : fatal error LNK1181: cannot open input file 'libsodium.lib'
    error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1181
```

**Environment**
- Windows Server 2012 R2 (on EC2)
- [Python 2.7.11](https://www.python.org/ftp/python/2.7.11/python-2.7.11.msi) and [VC++ for Python 27](http://aka.ms/vcpython27) are installed
- PyPy is downloaded from [official site](https://bitbucket.org/pypy/pypy/downloads/pypy-5.1.1-win32.zip)

**Note**

I've not tried http://zeromq.org/docs:windows-installations because I don't have idea how to build libzmq\builds\msvc\vs2008\libzmq.sln without Visual Studio. (32 bit version of VCBuild.exe doesn't seem to be included in VC++ for Python 27 so it is impossible to complete `C:\Windows\Microsoft.NET\Framework\v3.5\MSBuild.exe libzmq\builds\msvc\vs2008\libzmq.sln`.)

**Comment by minrk** [comment]
@sakurai-youhei can you try with pyzmq-15.3? I've never tried pypy on Windows, so there may well be some compilation/linking things overlooked for that case, but there are some changes to how bundled libzmq is built, which might help.

**Comment by sakurai-youhei** [comment]
@minrk I tried with the latest version but not changed so much. Importing zmq still requests sys/un.h.

**Commands to replicate**

```
msiexec /qn /i https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi ALLUSERS=1 ADDLOCAL=ALL
msiexec /qn /i https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi ALLUSERS=1 ADDLOCAL=ALL
python -m pip install wget
python -m wget https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.3.1-win32.zip
python -m zipfile -e pypy2-v5.3.1-win32.zip .

pypy2-v5.3.1-win32\pypy.exe -m ensurepip
pypy2-v5.3.1-win32\pypy.exe -m pip install --upgrade pip
pypy2-v5.3.1-win32\pypy.exe -m pip install -v https://github.com/zeromq/pyzmq/archive/v15.3.0.zip
pypy2-v5.3.1-win32\pypy.exe -c "import zmq"
```

**Results**
```
PS C:\Users\Administrator> pypy2-v5.3.1-win32\pypy.exe -c "import zmq"
_cffi_ext.c
pypy2-v5.3.1-win32\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(53) : fatal error C1083: Cannot open in
ile: 'sys/un.h': No such file or directory
Traceback (most recent call last):
  File "<module>", line 1, in <module>
  File "C:\Users\Administrator\pypy2-v5.3.1-win32\site-packages\zmq\__init__.py", line 56, in <module>
    from zmq import backend
  File "C:\Users\Administrator\pypy2-v5.3.1-win32\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Administrator\pypy2-v5.3.1-win32\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Administrator\pypy2-v5.3.1-win32\site-packages\zmq\backend\select.py", line 27, in select_backen
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Administrator\pypy2-v5.3.1-win32\site-packages\zmq\backend\cffi\__init__.py", line 6, in <module
    from zmq.backend.cffi import (constants, error, message, context, socket,
  File "C:\Users\Administrator\pypy2-v5.3.1-win32\site-packages\zmq\backend\cffi\constants.py", line 4, in <modul
    from ._cffi import C, c_constant_names
  File "C:\Users\Administrator\pypy2-v5.3.1-win32\site-packages\zmq\backend\cffi\_cffi.py", line 100, in <module>
    "Please check that you have zeromq headers and libraries." % e)
ImportError: PyZMQ CFFI backend couldn't find zeromq: CompileError: command 'C:\\Program Files (x86)\\Common File
osoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
Please check that you have zeromq headers and libraries.
```
See also attachment.

**Comment by alec-djinn** [comment]
I m having the same issue on OSX

```
machine:Desktop ***$ pypy start_jupyter.py notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
Traceback (most recent call last):
  File "start_jupyter.py", line 8, in <module>
    sys.exit(start_ipython())
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/IPython/terminal/ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/IPython/core/application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/IPython/terminal/ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/traitlets/config/application.py", line 488, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/IPython/core/application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/traitlets/config/application.py", line 419, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/notebook/notebookapp.py", line 31, in <module>
    from zmq.eventloop import ioloop
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/cffi/__init__.py", line 6, in <module>
    from zmq.backend.cffi import (constants, error, message, context, socket,
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/cffi/constants.py", line 4, in <module>
    from ._cffi import C, c_constant_names
  File "/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/cffi/_cffi.py", line 100, in <module>
    "Please check that you have zeromq headers and libraries." % e)
ImportError: PyZMQ CFFI backend couldn't find zeromq: Cannot load library /Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.pypy-41.so: dlopen(/Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.pypy-41.so, 2): Symbol not found: _zmq_bind
  Referenced from: /Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.pypy-41.so
  Expected in: flat namespace
 in /Users/***/Homebrew/Cellar/pypy/5.3.0/libexec/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.pypy-41.so
Please check that you have zeromq headers and libraries.
```

**Comment by sakurai-youhei** [comment]
@alec-djinn, Your comment gives me a bit idea. Mine is "sys/un.h" which is not available on Windows and yours  is "*.so" which should be probably "*.dylib" on Mac, right? Platform detection of pyzmq (or somewhere else) seems to be broken on PyPy; pyzmq might regard all of PyPy envs as running on Linux anyway. :-(

**Comment by alec-djinn** [comment]
@sakurai-youhei  "Platform detection of pyzmq (or somewhere else) seems to be broken on PyPy" I have the same feeling even though I cannot reproduce the same error in other Macs. Also, IPython is working well, only when starting the notebook it raises this error. That's really confusing to me...

**Comment by paul-pearce** [comment]
I'm also experiencing this issue under OSX 10.11.4. This seems to be an issue with pyzmq's bundled libzmq combined with pypy. Steps:

-pypy 5.4.1 via brew `brew install pypy`
-pyzmq via `pypy -m pip install pyzmq`

I then get the same error as @alec-djinn 

As a workaround if you install zeromq standalone (e.g. via brew) pyzmq no longer relies on its bundled libzmq, and all is right with the world. So:

-`pypy -m pip uninstall pyzmq`
-`brew install zeromq`
-`pypy -m pip install pyzmq`

**Comment by StevenMaude** [comment]
Have been working with a Windows user today trying to get Jupyter running.

This issue still exists with PyZMQ 16.0.1 under Windows/PyPy 5.4.1.

Following suggestions here, quickly tried installing ZeroMQ itself separately and reinstalling pyzmq, but didn't fix anything.

**Comment by LauriListak** [comment]
I ran into this issue under 64-bit Windows 10 when running `jupyter notebook` with Anaconda 4.3.1. However, `pip uninstall pyzmq` and `pip install pyzmq` did the work for me, even though pip warned me that

> DEPRECATION: Uninstalling a distutils installed project (pyzmq) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.

**Comment by johnashu** [comment]
@LauriListak 
> I ran into this issue under 64-bit Windows 10 when running jupyter notebook with Anaconda 4.3.1. However, pip uninstall pyzmq and pip install pyzmq did the work for me, even though pip warned me that

+2 .. I just solved the same error with this method.. thanks..

**Comment by dcabecinhas** [comment]
The problem still persists. The @paul-pearce workaround solved it for me.

**Comment by lassoan** [comment]
This is still an issue (Windows 10, 64-bit Anaconda downloaded on 2018-11-15).

Workaround proposed by @LauriListak solved the issue.

**Comment by AhmedTremo** [comment]
The problem isn't solved with me till now

**Comment by sakurai-youhei** [comment]
Because Python 2.7 is no longer supported, I have checked this with pypy3 again.

**Windows**: 10.0.18363
**pypy3**: https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.0-win32.zip
**pyzmq**: pyzmq-19.0.0

And, I'd say nothing seems to have been changed so far; cl.exe reports **C1083** due to **missing `sys/un.h`**.

```
C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32>pypy3 -m ensurepip
Looking in links: c:\Users\sakurai\AppData\Local\Temp\tmpcubp4vct
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-19.2.3 setuptools-41.2.0

C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32>pypy3 -m pip install pyzmq
Collecting pyzmq
  Downloading https://files.pythonhosted.org/packages/16/4c/762c2c3063c4d45baf4a49acea7a4f561f7b78a45cd04b58d63f4c5f6b8d/pyzmq-19.0.0.tar.gz (1.2MB)
     |################################| 1.2MB 384kB/s
Collecting py (from pyzmq)
  Downloading https://files.pythonhosted.org/packages/99/8d/21e1767c009211a62a8e3067280bfce76e89c9f876180308515942304d2d/py-1.8.1-py2.py3-none-any.whl (83kB)
     |################################| 92kB 1.5MB/s
Requirement already satisfied: cffi in c:\users\sakurai\desktop\pypy3.6-v7.3.0-win32\lib_pypy (from pyzmq) (1.13.2)
Installing collected packages: py, pyzmq
  Running setup.py install for pyzmq ... done
Successfully installed py-1.8.1 pyzmq-19.0.0
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32>pypy3 -c "import zmq"
_cffi_ext.c
site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(56): fatal error C1083: include ファイルを開けません。'sys/un.h':No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32\site-packages\zmq\backend\cffi\__init__.py", line 6, in <module>
    from zmq.backend.cffi import (constants, error, message, context, socket,
  File "C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32\site-packages\zmq\backend\cffi\constants.py", line 4, in <module>
    from ._cffi import C, c_constant_names
  File "C:\Users\sakurai\Desktop\pypy3.6-v7.3.0-win32\site-packages\zmq\backend\cffi\_cffi.py", line 100, in <module>
    "Please check that you have zeromq headers and libraries." % e)
ImportError: PyZMQ CFFI backend couldn't find zeromq: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
Please check that you have zeromq headers and libraries.
```

**Comment by sinanb** [comment]
I am experiencing the same issue with @sakurai-youhei 

`pip install/uninstall pyzmq` does not help for this case.

**Comment by mattany** [comment]
I have the same issue when trying to configure the jupyter notebook kernel in pycharm on windows 10

**Comment by Johannes0Horn** [comment]
I can import zmq on win 10 ,anaconda Python 3.7. However when i try to make it part of an executable via pyinstaller i get the exact same issue about missing sys/un.h.
pip install/uninstall pyzmq does not help me in this case. 
Had anybody success with @sakurai-youhei´s fix? To me it leads to a new error: 
```
"c:\programdata\anaconda3\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(267):
'zmq.h': not found!"
```

**Comment by sakurai-youhei** [comment]
To those who encounter the error out of PyPy (like @Johannes0Horn )

You shouldn't be annoyed by this issue because [primary backend of pyzmq is not cffi but cython](https://github.com/zeromq/pyzmq/blob/v19.0.0/zmq/backend/__init__.py#L24) on your e.g. CPython, anaconda, etc.

If you see the same or similar error out of PyPy, please check out what error occurs when setting `PYZMQ_BACKEND=cython` in environmental variable, which disables implicit fallback of pyzmq backend from cffi to cython (i.e. it enforces use of cython backend).

My reporting issue should be applicable only for PyPy.

**Comment by mzy2240** [comment]
> I can import zmq on win 10 ,anaconda Python 3.7. However when i try to make it part of an executable via pyinstaller i get the exact same issue about missing sys/un.h.
> pip install/uninstall pyzmq does not help me in this case.
> Had anybody success with @sakurai-youhei´s fix? To me it leads to a new error:
> 
> ```
> "c:\programdata\anaconda3\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(267):
> 'zmq.h': not found!"
> ```

@Johannes0Horn Did you find the solution for the issue you mentioned? I am having the same issue right now. The pyinstaller cannot work with pyzmq even if I downgrade the pyzmq version.

**Comment by alec-djinn** [comment]
Have you tried giving it the requested file? https://github.com/zeromq/libzmq/blob/master/include/zmq.h <https://github.com/zeromq/libzmq/blob/master/include/zmq.h>

**Comment by Johannes0Horn** [comment]
@mzy2240 As @sakurai-youhei mentioned this error probalby shouldnt bother us. At least i can tell it turned out it wasnt an issue for me.

If i create a new python 3.7 env on win 10 64 bit and install zmq and pyinstaller i also can `import zmq` using the python and pyinstaller version without any error.
pyzmq: 19.0.0
pyinstaller: 3.6

Does this work for you?

**Comment by mzy2240** [comment]
@Johannes0Horn That's also what I am expecting! Awesome! BTW just to clarify, does it have to be a new environment? How about a new venv or a new conda venv?

**Comment by Johannes0Horn** [comment]
@mzy2240 i used conda

**Comment by mzy2240** [comment]
@Johannes0Horn Thanks! One more thing, did you use custom spec file or just the default config when packaging?

**Comment by Johannes0Horn** [comment]
no custom spec, nothing else modified

**Comment by mzy2240** [comment]
@Johannes0Horn Thanks! It is working now! Great!

**Comment by suamin** [comment]
I was facing the same issue when opening jupyter notebook:
```
_cffi_ext.c
D:\dev\programs\anaconda3\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(268): fatal error C1083: Cannot open include file: 'zmq.h': No such file or directory
Traceback (most recent call last):
  File "D:\dev\programs\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "D:\dev\programs\anaconda3\lib\site-packages\notebook\notebookapp.py", line 51, in <module>
    from zmq.eventloop import ioloop
  File "D:\dev\programs\anaconda3\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "D:\dev\programs\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "D:\dev\programs\anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "D:\dev\programs\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "D:\dev\programs\anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "D:\dev\programs\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.
```
The `pip install/uninstall pyzmq` did not work for me. Running `conda install jupyter` resolved the issue (note all of these steps were performed while in a conda virtual environment).
