### ISSUE TITLE
Pyzmq -  from . import (constants, error, message, context, (Termux on Android) 

### ISSUE THREAD

**Issue by brubakerjeff** [zeromq/pyzmq#1240]
Hi,
I'm working on a program that imports Pyzmq. I upgraded to pyzmq-17.1.2 installed through pip. The base program is running through python 2.7, inside of termux and pyzmq was installed through pip. I'm receiving the following error. I isolated it to the following. Any help or pointers would be appreciated. Should the python3.7 work with python2.7 as well, or should I perhaps be using an older version? 

pyzmq is installed using 
pip install pyzmq (also tried with adding  --install-option="--zmq=bundled")

Is this configuration working a zmq dependency? Is there an easy way to install that with termux?

--- test .py

```python
import zmq
print('do nothing')
```

```
$ python2 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import zmq
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name constants
```

python3 appears to give more details

```
python3 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import zmq
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen failed: cannot locate symbol "zmq_strerror" referenced by "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/cython/error.cpython-37m.so"...
```

**Comment by minrk** [comment]
They key is probably that Python 2 is importing Python 3 packages. That's not going to work. Can you find why your Python 2 is importing from `.../python3.7/site-packages`? Can you uninstall pyzmq and include the full output of `pip install --no-cache -v pyzmq`? Do you have any `*PATH` environment variables set (`env | grep PATH | sort`) that might be relevant?

**Comment by brubakerjeff** [comment]
Thank you. Trying to understand this better. Does pip perform low level compilation tasks?

This makes me think it is a low level library compatibility concern.
ImportError: dlopen failed: cannot locate symbol "zmq_strerror" referenced by "/data/data/com.termux/files/usr/lib/python2.7/site-packages/zmq/backend/cython/error.so"...

Full output.
https://gist.github.com/brubakerjeff/e34bfc4b0cefc772bb981e42f5e4a536

**Comment by minrk** [comment]
Ah, this is arm on android. That's probably relevant, and might have some consequences for building. You might have better luck building libzmq itself from source and then linking pyzmq to it instead.

**Comment by brubakerjeff** [comment]
digging on this 
`` make
Making all in src
make[1]: Entering directory '/data/data/com.termux/files/home/zeromq3-x/src'
make  all-am
make[2]: Entering directory '/data/data/com.termux/files/home/zeromq3-x/src'
  CXX      libzmq_la-address.lo
  CXX      libzmq_la-clock.lo
  CXX      libzmq_la-ctx.lo
  CXX      libzmq_la-decoder.lo
  CXX      libzmq_la-devpoll.lo
  CXX      libzmq_la-dist.lo
  CXX      libzmq_la-encoder.lo
  CXX      libzmq_la-epoll.lo
  CXX      libzmq_la-err.lo
  CXX      libzmq_la-fq.lo
  CXX      libzmq_la-io_object.lo
  CXX      libzmq_la-io_thread.lo
  CXX      libzmq_la-ip.lo
  CXX      libzmq_la-ipc_address.lo
  CXX      libzmq_la-ipc_connecter.lo
  CXX      libzmq_la-ipc_listener.lo
ipc_listener.cpp:124:17: error: 'tempnam' is deprecated: tempnam is unsafe, use
      mkstemp or tmpfile instead [-Werror,-Wdeprecated-declarations]
        addr_ = tempnam(NULL, NULL);
                ^
/data/data/com.termux/files/usr/include/stdio.h:173:5: note: 'tempnam' has been
      explicitly marked deprecated here
    __warnattr("tempnam is unsafe, use mkstemp or tmpfile instead");
    ^
/data/data/com.termux/files/usr/include/sys/cdefs.h:160:40: note: expanded from
      macro '__warnattr'
#define __warnattr(msg) __attribute__((deprecated(msg)))
                                       ^
1 error generated.
make[2]: *** [Makefile:878: libzmq_la-ipc_listener.lo] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/zeromq3-x/src'
make[1]: *** [Makefile:590: all] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/zeromq3-x/src'
make: *** [Makefile:418: all-recursive] Error 1
$ make install
Making install in src
make[1]: Entering directory '/data/data/com.termux/files/home/zeromq3-x/src'
  CXX      libzmq_la-ipc_listener.lo
ipc_listener.cpp:124:17: error: 'tempnam' is deprecated: tempnam is unsafe, use
      mkstemp or tmpfile instead [-Werror,-Wdeprecated-declarations]
        addr_ = tempnam(NULL, NULL);
                ^
/data/data/com.termux/files/usr/include/stdio.h:173:5: note: 'tempnam' has been
      explicitly marked deprecated here
    __warnattr("tempnam is unsafe, use mkstemp or tmpfile instead");
    ^
/data/data/com.termux/files/usr/include/sys/cdefs.h:160:40: note: expanded from
      macro '__warnattr'
#define __warnattr(msg) __attribute__((deprecated(msg)))
                                       ^
1 error generated.
make[1]: *** [Makefile:878: libzmq_la-ipc_listener.lo] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/zeromq3-x/src'
make: *** [Makefile:418: install-recursive] Error 1
``

**Comment by minrk** [comment]
It might be worth getting the latest (4.2.5) sources for libzmq as [linked here](http://zeromq.org/intro:get-the-software#toc2). 3.x is pretty far back now.

**Comment by brubakerjeff** [comment]
Thank you. I had worked towards 4.2.5 (
https://github.com/zeromq/libzmq/issues/3307) and now have a different error in configure.

checking whether to install manpages... no
./configure: 21048: test: x: unexpected operator
./configure: 21053: test: unexpected operator
configure: Choosing polling system from ''...
configure: error: None of '' are valid pollers on this platform

configure:21048
if test "x$with_poller" == "x"; then
pollers=auto
else
pollers=$with_poller
fi
if test "$pollers" == "auto"; then
# We search for pollers in this order
pollers="kqueue epoll devpoll pollset poll select"

**Comment by brubakerjeff** [comment]
Just tried on lineageos 14.1 (Android 7.1) on flex (Nexus 7) and have same error. Thinking inline with your comment android is the relevant variable.

**Comment by brubakerjeff** [comment]
@mink after a lot of work I was able to compile zmq. I can run in c but still struggling with the pyzmq wrapper. Any pointers? Does pip2 do any compilation work?
$ cat test.c
//  Hello World client
#include <zmq.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>

int main (void)
{
    printf ("Connecting to hello world server…\n");
    void *context = zmq_ctx_new ();
    void *requester = zmq_socket (context, ZMQ_REQ);
    zmq_connect (requester, "tcp://localhost:5555");

    int request_nbr;
    for (request_nbr = 0; request_nbr != 10; request_nbr++) {
        char buffer [10];
        printf ("Sending Hello %d…\n", request_nbr);
        zmq_send (requester, "Hello", 5, 0);
        zmq_recv (requester, buffer, 10, 0);
        printf ("Received World %d\n", request_nbr);
    }
    zmq_close (requester);
    zmq_ctx_destroy (context);
    return 0;
}
$ gcc test.c -lzmq -latomic -o test
$ ./test
Connecting to hello world server…
Sending Hello 0…

$ pip2 install pyzmq
Requirement already satisfied: pyzmq in /data/data/com.termux/files/usr/lib/python2.7/site-packages
$ cat test.py
import zmq
$ python2 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import zmq
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen failed: cannot locate symbol "zmq_strerror" referenced by "/data/data/com.termux/files/usr/lib/python2.7/site-packages/zmq/backend/cython/error.so"...

**Comment by brubakerjeff** [comment]
Reran and still receive the same error.
https://gist.github.com/brubakerjeff/3bc6810f55c315d96fecdfc5f8c69e01

**Comment by brubakerjeff** [comment]
Here are my commands now. Started from clean image
git clone libzmq
./autogen.sh
Update libzmq tipc configure.ac
./configure --with-poller=epoll --prefix=/data/data/com.termux/files/usr
Makefile:1866: LIBS = -lrt -lpthread *-latomic *
make N=1
git clone pyzmq
cd pyzmq
python2 setup.py configure --zmq=/data/data/com.termux/files/home/libzmq
python2 setup.py install

breaks on
python2 setup.py configure --zmq=/data/data/com.termux/files/home/libzmq



running configure
{'libraries': ['zmq'], 'extra_link_args': [], 'runtime_library_dirs': ['/data/data/com.termux/files/home/libzmq/lib'], 'library_dirs': ['/data/data/com.termux/files/home/libzmq/lib'], 'include_dirs': ['/data/data/com.termux/files/home/libzmq/include']}
************************************************
Configure: Autodetecting ZMQ settings...
    Custom ZMQ dir:       /data/data/com.termux/files/home/libzmq
creating build/temp.linux-armv7l-2.7/scratch/data
creating build/temp.linux-armv7l-2.7/scratch/data/data
creating build/temp.linux-armv7l-2.7/scratch/data/data/com.termux
creating build/temp.linux-armv7l-2.7/scratch/data/data/com.termux/files
creating build/temp.linux-armv7l-2.7/scratch/data/data/com.termux/files/usr
creating build/temp.linux-armv7l-2.7/scratch/data/data/com.termux/files/usr/tmp
arm-linux-androideabi-clang -fno-strict-aliasing -OPT:Olimit=0 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -c /data/data/com.termux/files/usr/tmp/timer_create_41jip.c -o build/temp.linux-armv7l-2.7/scratch/data/data/com.termux/files/usr/tmp/timer_create_41jip.o
/data/data/com.termux/files/usr/tmp/timer_create_41jip.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
main (int argc, char **argv) {
^
/data/data/com.termux/files/usr/tmp/timer_create_41jip.c:2:5: warning: implicit declaration of function 'timer_create' is invalid in C99 [-Wimplicit-function-declaration]
    timer_create();
    ^
/data/data/com.termux/files/usr/tmp/timer_create_41jip.c:2:5: warning: this function declaration is not a prototype [-Wstrict-prototypes]
3 warnings generated.
arm-linux-androideabi-clang build/temp.linux-armv7l-2.7/scratch/data/data/com.termux/files/usr/tmp/timer_create_41jip.o -o build/temp.linux-armv7l-2.7/scratch/a.out
arm-linux-androideabi-clang -fno-strict-aliasing -OPT:Olimit=0 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/data/com.termux/files/home/libzmq/include -Izmq/utils -Izmq/backend/cython -Izmq/devices -c build/temp.linux-armv7l-2.7/scratch/vers.c -o build/temp.linux-armv7l-2.7/scratch/vers.o
arm-linux-androideabi-clang build/temp.linux-armv7l-2.7/scratch/vers.o -L/data/data/com.termux/files/home/libzmq/lib -R/data/data/com.termux/files/home/libzmq/lib -lzmq -o build/temp.linux-armv7l-2.7/scratch/vers
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/bin/../lib/libzmq.a(libzmq_la-socket_base.o): in function `zmq::socket_base_t::create(int, zmq::ctx_t*, unsigned int, int)':
/data/data/com.termux/files/home/libzmq/src/socket_base.cpp:113: undefined reference to `operator new(unsigned int, std::nothrow_t const&)'
