### ISSUE TITLE
cannot import name 'constants'

### ISSUE THREAD

**Issue by ben-albrecht** [zeromq/pyzmq#703]
Running Python 3.5, just upgraded pyzmq to 14.7.0, and it now throws an error when imported. See output below:

```
Python 3.5.0a3 (v3.5.0a3:82656e28b5e5, Mar 29 2015, 15:59:31) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants
```

**Comment by ben-albrecht** [comment]
I uninstalled 14.7.0 then installed pyzmq==14.5.0, and it works fine now. Hope this helps in finding the problem.

**Comment by minrk** [comment]
Can you try with a more recent Python 3.5? a3 had some problems with imports. Current is 3.5b3. The test suite is passing regularly with 3.5 now.

**Comment by ben-albrecht** [comment]
Good call - works fine with Python 3.5.0b3

**Comment by minrk** [comment]
Thanks.

**Comment by ozh** [comment]
I'm having the same error message, can anyone explain me in noob terms how I might fix this?

So far, `python --version` gives `Python 3.5.1` and `python -m easy_install pyzmq` says `pyzmq 14.4.0` is installed
