### ISSUE TITLE
Build on FreeBSD 9.3 fails

### ISSUE THREAD

**Issue by thul** [zeromq/pyzmq#716]
Running the following command will result in a failed install:

    pip install pyzmq --install-option="--zmq=bundled"
    .... wall of text ...
    bundled/zeromq/src/ip.cpp: In function 'zmq::fd_t zmq::open_socket(int, int, int)':

    bundled/zeromq/src/ip.cpp:54: error: 'SOCK_CLOEXEC' was not declared in this scope

    error: command 'cc' failed with exit status 1

    ----------------------------------------
    Command "/usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-G3MLbr/pyzmq/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LBegER-record/install-record.txt --single-version-externally-managed --compile --zmq=bundled" failed with error code 1 in /tmp/pip-build-G3MLbr/pyzmq

How can i solve this issue?

**Comment by minrk** [comment]
Try this:

```bash
git clone https://github.com/zeromq/pyzmq.git -b v14.7.0
cd pyzmq
python setup.py fetch_libzmq
python setup.py configure --zmq=bundled
python setup.py install
```

**Comment by fujiaoliu** [comment]
what if the machine can't connect the public network,  how should I do when  "bundled/zeromq/src/ip.cpp:54: error: ‘SOCK_CLOEXEC’ was not declared in this scope
error: command 'gcc' failed with exit status 1"  happend?

**Comment by nocrosstalk** [comment]
This worked for me - finally. Thank's for that. Though when I import zmq in python I get following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name constants

**Comment by minrk** [comment]
When you are testing, make sure that you are not in the zmq repo. `cd ~` first, or something else.

**Comment by nocrosstalk** [comment]
Stupid me, right, correct, thank's 1000x

**Comment by nimeshreddy** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name constants
I am getting the same error. What could the probable reason.
